name: pointify
description: reggy pos

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  math_expressions: ^2.3.0
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.4
  open_file: ^3.2.1
  mime: ^1.0.2
  switcher_button: ^0.0.4
  intl:
  date_time_picker: ^2.1.0
  pdf: ^3.10.1
  path_provider: ^2.0.11
  syncfusion_flutter_pdf: ^20.2.39
  shimmer: ^2.0.0
  flutter_barcode_scanner: ^2.0.0
  barcode_widget: ^2.0.3
  flutter_svg: ^1.1.4
  font_awesome_flutter: ^10.1.0
  syncfusion_flutter_charts: ^20.3.48
  f_datetimerangepicker: ^0.2.0
  flutter_datetime_picker: ^1.5.1
  autocomplete_textfield: ^2.0.1
  url_launcher: ^6.1.10
  realm: 1.0.0
  syncfusion_flutter_datepicker:
  data_table_2: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Helvetica.ttf