name: pointify
description: reggy pos

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.4
  open_file: ^3.2.1
  mime: ^1.0.2
  switcher_button: ^0.0.4
  path_provider: ^2.0.15
  permission_handler: ^10.3.0
  intl:
  pdf: ^3.10.4
  shimmer: ^2.0.0
  flutter_barcode_scanner: ^2.0.0
  barcode_widget: ^2.0.3
  syncfusion_flutter_charts: ^20.3.48
  url_launcher: ^6.1.10
  realm: 1.0.0
  syncfusion_flutter_datepicker:
  data_table_2: ^2.5.3
  printing: ^5.11.0
  excel: 2.1.0
  syncfusion_flutter_xlsio:
  file_picker: ^5.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Helvetica.ttf