name: flutterpos
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  math_expressions: ^2.3.0
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.4
  shared_preferences:
  open_file: ^3.2.1
  mime: ^1.0.2
  switcher_button: ^0.0.4
  syncfusion_flutter_datepicker: ^20.2.44
  intl: ^0.17.0
  date_time_picker: "^2.1.0"
  pdf: ^3.8.1
  path_provider: ^2.0.11
  modal_bottom_sheet: ^2.1.0
  syncfusion_flutter_pdf: ^20.2.39
  shimmer: ^2.0.0
  share_plus: ^4.1.0
  url_launcher: ^6.1.5
  flutter_barcode_scanner: ^2.0.0
  barcode_widget: ^2.0.3
  connectivity_plus: ^2.3.7
  google_nav_bar: ^5.0.6
  flutter_svg: ^1.1.4
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  syncfusion_flutter_charts: ^20.3.48
  f_datetimerangepicker: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

