name: flutterpos
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_svg: ^1.1.4
  google_fonts: ^3.0.1
  http: ^0.13.5
  shared_preferences:
  path_provider: ^2.0.11
  switcher_button: ^0.0.4
  google_nav_bar: ^5.0.6
  modal_bottom_sheet: ^2.1.0
  cupertino_icons: ^1.0.2
  flutter_barcode_scanner: ^2.0.0
  barcode_widget: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

